#!/usr/bin/python3

import mwclient
import secrets
import json

user_agent = 'UpdateMaintenancePage'
site = mwclient.Site('wiki.lvl1.org', path='/')
site.login(secrets.username, secrets.password)
print(site)
page = site.pages["Automated_maintenance_report"]

file = open('reports.json', 'r')
reports = json.loads(file.read())
file.close()

wiki_text ='{|\n' + '|+ Maintenance Due\n' 
wiki_text = wiki_text + '|-\n'
wiki_text = wiki_text + '! Maintenance !! Overdue !! Current Day !! Maintenance Interval\n'
wiki_text = wiki_text + '|-\n'
for i in reports.keys():
    wiki_text = wiki_text + '| ' + reports[i]["NAME"] + '||' +str(reports[i]["OVERDUE"])+ '||' + str(reports[i]["CURRENT"]) + '||' + str(reports[i]["PERIOD"]) + '\n'
    wiki_text = wiki_text + '|-\n'
wiki_text = wiki_text + '|}'
print(wiki_text)



page.edit(wiki_text, 'Autogenerated maintenance update')
